### PR TITLE
fix issue 376 Profile Picture can only be changed by user

### PR DESCRIPTION
**Pull request by ramgarden**
closes issue #376 Changed profile picture module so that it only allows a
user to upload a photo for their own profile unless they have a role
with contact_edit permissions.

### CODE REVIEW

**Comment by chris18890** [comment]
This PR has other mods for the membership module, a new branch for this specific issue should be created from the current @elpatt/dev branch, patched & then PR'd

**Comment by elplatt** [comment]
Like Chris said, it would have been better to break this up into separate pull requests, but I'll merge it since there are no conflicts and it doesn't change core.

**Comment by ramgarden** [comment]
What was the other change?  I might have put it in there on accident.

**Comment by ramgarden** [comment]
Oh I see my fix for #354 is in this one too.  I thought I had that pull request already in the pipe?

**Pull request merged**
