### PR TITLE
add createdBy attribute - closes #357 - v0.6.0

### LINKED ISSUE #357: Feature request: View "entered by" data as part of a member's normal record view.
Currently, Seltzer sends out an email when a new contact is created, and at the bottom of the email, it shows who did the creation. Is that data stored anywhere? If so, could it be displayed as part of a member's contact view?

### PR DESCRIPTION
**Pull request by chris18890**
add createdBy attribute - closes #357 - v0.6.0

### CODE REVIEW

**Comment by chris18890** [comment]
@elplatt  / @ramgarden another one for yous to review!

**Comment by chris18890** [comment]
This is the email view

image

image

**Comment by ramgarden** [comment]
How does a person self register?

**Comment by chris18890** [comment]
If the “register” module is enabled, there’s a “register” link at the top right side beside login & reset password :)

**Comment by ramgarden** [comment]
OH! I guess we've never used the register module since all new members go
through our secretary/admin handful of users.

**Comment by chris18890** [comment]
@ramgarden you should upgrade to the latest release of master & give it a go :P

**Comment by chris18890** [comment]
@ramgarden @elplatt do you think it's worth adding createdDate & createdTime attributes to contacts as well, & adding these attributes to plans/keys etc?

**Comment by ramgarden** [comment]
I'd say keys and plans don't need the create date since they have start
date.
But I can see rare cases where a new member might set their membership to
start in the future.
So in that case the create date would be different than start date.
At Melbourne Makerspace we always add new members right on their start day.
But there might get be cases where we would want to add the contact but
they won't really start a paid membership until next week or next month.
Perhaps adding these fields would be good to have?
Do we need to worry about the extra data storage it adds for those hosting
on servers with DB quotas for free tiers?

**Comment by chris18890** [comment]
@ramgarden  I was thinking more about adding the createdDate to the plan object itself, the start date refers to the membership which is the link between plans & members IIRC.

As for the data storage, I hadn't really considered that TBH, I wouldn't've thought it'd take up that much more space...

**Pull request merged**
