### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ramgarden**
Fixed issue #354.  I also added a simple /api folder where 3rd party apps and IoT devices could easily query the Seltzer DB to check if a member's RFID key is OK and if they have paid their dues, etc.

### CODE REVIEW

**Comment by chris18890** [comment]
hey @ramgarden!

I reviewed & the code looks ok, but :-1: from me for the following 2 reasons -

* PRs should avoid being made against the master branch, they should be made against "develop", to ensure that whatever is in master is functioning & deployable, & then merged into master with an associated version number bump. See [this github link](https://guides.github.com/introduction/flow/index.html) for more info on branching and [the semantic version spec](http://semver.org/) for more on version numbers

* A PR should generally deal with a specific issue.  While I think the REST API is a brilliant idea, in this case I'd focus on dealing with the issue, & making the REST stuff a separate pull request.

I also don't have write access to the repo, so it's @ELPlatt who gets final say on the code

**Comment by ramgarden** [comment]
Thanks for the review!  All my experience is with SVN and Tortoise SVN.  So this is my very first PR ever.  I'll make sure to take out the REST API stuff and just do this one fix and do the PR against the develop branch.  Thanks for the links - I'll read up on those first too.

**Comment by ramgarden** [comment]
I'm assuming we are using the "dev" branch and not the "dev-0.4" branch, right?

**Comment by chris18890** [comment]
@ramgarden Fair enough, I'm the other way around, i started off using git first & have thus far successfully avoided CVS & SVN :P
 
Yeah, the "dev" branch is the one to work from :)

**Comment by ramgarden** [comment]
Did my fixes for this issue make it into the right place? Anything left for me to do?

**Pull request closed without merging**
