### PR TITLE
move contact_list install from contact to user #413

### PR DESCRIPTION
**Pull request by chris18890**
move contact_list install from contact to user #413

### CODE REVIEW

**Comment by chris18890** [comment]
@elplatt @ramgarden review requested to merge

Tested by nuking my test DB & install, then deploying a copy of branch issue_413 then running the install

**Comment by ramgarden** [comment]
Will review this later tonight.

**Comment by ramgarden** [comment]
Looks like an easy fix. What will happen if people are upgrading to 0.5.5? Will the ever be a case where someone gets stuck in the middle? Any way they can have the DB in a non- upgradable state? It would be bad if anyone was on a certain version and the only way to upgrade would be to backup and nuke their db first.  Is this possible or all good?

**Comment by chris18890** [comment]
@ramgarden that's what I'm gonna test, there are 5 scenarios

- [ ] clean install from master, upgrade to dev branch
- [ ] clean install from dev branch
- [ ] clean install from master, upgrade to issue_413 branch
- [ ] clean install from issue_413 branch
- [ ] clean install from master, upgrade to dev branch, upgrade to issue_413 branch

**Comment by chris18890** [comment]
@elplatt @ramgarden I've hacked together a patch for the permissions within user.inc.php

The following scenarios have been re-tested

- [ ] 3. clean install from master, upgrade to issue_413 branch :+1:
- [ ] 4. clean install from issue_413 branch :+1:
- [x] 5. clean install from master, upgrade to dev branch, upgrade to issue_413 branch :+1:

**Pull request merged**
