### PR TITLE
Remove read-only username field & rename section

### PR DESCRIPTION
**Pull request by chris18890**
Remove read-only username field & rename section

Before

image

After

image

### CODE REVIEW

**Comment by chris18890** [comment]
@elplatt @ramgarden any objections to this?

**Comment by ramgarden** [comment]
Why was this removed?

**Comment by chris18890** [comment]
It seemed superfluous as it's on the view tab and was a read only field I just thought the form looked (c)leaner without it

**Comment by ramgarden** [comment]
Does the username show on a different form anywhere else?  It's good to know.

**Comment by chris18890** [comment]
It's visible on the view tab of the user profile, and will be listed in joining emails etc; the app generally renders the user's name in a surname,  firstname (middle name) format, and the user can log in with their email address as well as username

**Comment by ramgarden** [comment]
ah OK then this is a great idea!  Ship it!

**Comment by chris18890** [comment]
Will merge on Friday to give others time to comment

**Pull request merged**
