### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ramgarden**
Fixed issue #354.  Setting the membership end date to something in the future no longer considers the member to be inactive.

### CODE REVIEW

**Comment by chris18890** [comment]
hey @ramgarden.  the PR should have been made against your version of Dev to the main version of Dev, not Master; sorry if I didn't make that clear!.  Not sure if @elplatt can fix that or if you need to do another PR.

**Comment by ramgarden** [comment]
Did my fix for membership end date make it to the right place?  Or is there something left for me to do for that fix?

**Comment by elplatt** [comment]
PR had conflicts and was made against master, so it was not accepted. See TLDR here: https://github.com/elplatt/seltzer/wiki/Developer-guidelines

**Comment by chris18890** [comment]
Hey @ramgarden, if you open a new pull request against the updated Dev branch I'm happy to work with you on getting it QA'd :)

**Comment by ramgarden** [comment]
I might need a webex or hangout help to make sure I'm doing it right!  :)

**Comment by chris18890** [comment]
@ramgarden sure thing! I'm available most of today (Sunday) & tomorrow, my details are in the contributors file, drop me an email & we can schedule something :)

**Comment by chris18890** [comment]
@ramgarden I've taken care of this via PR #360, just waiting for review/merging by @elplatt

**Comment by ramgarden** [comment]
Thanks!  I guess I still need to read through the steps to make sure I'm
making the fixes against the right branch etc.

**Pull request closed without merging**
