### PR TITLE
release v0.7.2

### PR DESCRIPTION
**Pull request by chris18890**
Thiss release contains a substancial re-write to remove the use of global variables & encapsule them in helper functions, adding helper functions of rmost of the values in the global `config.inc.php` file; it also adds a new options page to managed these varibales.

By default, the "Director" & "WebAdmin" roles have view access, but only the built-in "admin" account has edit access

WARNING - changing these values can render your your installion unusable, & may not be fixable without access to tthe web server and/or MySQL DB

### CODE REVIEW

**Comment by chris18890** [comment]
PR please @elplatt / @ramgarden ?

**Comment by ramgarden** [comment]
What's that warning about breaking the DB about?

**Review by ramgarden — APPROVED** [review]
Nice clean up of whitespace and spelling errors.
See my earlier comment on that DB breaking warning in the PR description.

**Comment by chris18890** [comment]
It's if, for example, someone were to misspell or put a wrong value in for "host", "base path" or "theme, it can break things, might need to make some fields read-only. It's only an issue if you're using the built-in admin account or have specifically given 'global_options_edit' permissions, I tried to mitigate it by not giving anyone edit permissions by default.

**Pull request merged**
