### PR TITLE
Issue #346 @mjgardes integration

### PR DESCRIPTION
**Pull request by chris18890**
Issue #346 @mjgardes integration

### CODE REVIEW

**Comment by elplatt** [comment]
Why the switch from cid to amazon_name?

**Comment by elplatt** [comment]
Looks like this has conflicts, also still not sure why the switch to amazon_name. Is this still open, or should I close it?

**Comment by chris18890** [comment]
probably due to the other PRs being merged, I'm not sure either, it was a fix that @mjgardes had put in place on their fork, I'll review this :)

**Comment by mjgardes** [comment]
That was a long time ago... We stopped trying to map amazon usernames to cids when amazon killed the flexible payments system.  I wanted to get rid of the amazon module entirely since we've added a middleman service to deal with evolving payment gateways for us but it turns out that there are still features in that module that we use.

**Comment by chris18890** [comment]
closing this, as the typo clean-ups & minor improvements have been been incorporated into #386 & @mjgardes' other amazon-specific fixes have been disregarded

**Pull request closed without merging**
